{
 "title": "Router",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "severity",
    "query": {}
   },
   { "name": "filter" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Events by Severity over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=\"syslog\", severity=~\"$severity\"} |= `$filter` [$__auto])) by (severity)",
     "legendFormat": "{{detected_level}}"
    }
   ]
  },
  {
   "title": "Events by App and Severity",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(appname, severity) (count_over_time({service_name=\"syslog\", severity=~\"$severity\"}  |= `$filter` [$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"syslog\", severity=~\"$severity\"} |= `$filter`"
    }
   ]
  }
 ]
}